### PR TITLE
Hapi Rewrite

### PR DESCRIPTION
**Pull request by wbprice**
To start, use Overpass API to get all the data in a bounding box.

### CODE REVIEW

**Comment by ryayak1460** [comment]
Looks good, just need to add the license file back.

We decided at Stella's to use Affero since we don't know if this would go over 300 lines, so I'll change that and you can merge that change in if you like  before we merge this request.

**Comment by wbprice** [comment]
@ryayak1460 I added the Affero license and pushed up that commit.

**Comment by stanzheng** [comment]
:+1: rebase needed

**Comment by ryayak1460** [comment]
Only one thing: we need to return exhibits without requiring a query parameter.  Ember.js will want to use the /exhibits route like a model call, so we can't include a bounding box in the request.  I forgot about that part, sorry.

Past that, dude, @wbprice: awesome work.  OpenShift, Hapi.js rewrite, functional code and Affero? Hell yeah!

**Comment by wbprice** [comment]
@ryayak1460 what should a call to /exhibits without any querystring return?

**Comment by ryayak1460** [comment]
All exhibits.

On 13 January 2015 08:51:14 GMT-05:00, "W. Blaine Price" <notifications@github.com> wrote:
>@ryayak1460 what should a call to /exhibits without any querystring
>return?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Code4HR/local-art-api/pull/27#issuecomment-69746293

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by wbprice** [comment]
@ryayak1460 That can be done, but my concern is the the app won't scale well if we're not limiting response size. This person does something with query strings:
http://stackoverflow.com/questions/16506634/ember-route-with-dynamic-filter-search-criterias

**Pull request merged**
